version: '3.9'

services:
  phpmyadmin:
    image: phpmyadmin:5
    restart: unless-stopped
    networks:
      - app
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1 # https://hub.docker.com/_/phpmyadmin
networks:
  app:
    external: true
    name: app